import numpy as np

from fossen_solver import Fossen6DOFParams, R_n_to_b, wrap_to_pi, wrap_euler_error

class ThrusterAllocator:
    """
    Maps thruster commands into a BODY-frame wrench and provides
    allocation path from desired wrench to feasible thruster commands.

    Current thrust model:
        f_i = k_i * |n_i| * n_i
        tau = B @ f

    where:
        n : thruster speed command vector
        f : per-thruster force vector
        B : allocation matrix
    """

    def __init__(self, B: np.ndarray, k_thrusters: np.ndarray, n_max: np.ndarray = None):
        self.B = np.asarray(B, dtype=float)
        self.k_thrusters = np.asarray(k_thrusters, dtype=float).reshape(-1)

        if self.B.ndim != 2:
            raise ValueError("B must be 2D.")
        if self.B.shape[0] != 6:
            raise ValueError("B must have shape (6, m).")
        if self.B.shape[1] != self.k_thrusters.size:
            raise ValueError("k_thrusters length must match number of thrusters.")

        if np.any(self.k_thrusters <= 0.0):
            raise ValueError("k_thrusters must be positive.")

        if n_max is None:
            self.n_max = np.full(self.k_thrusters.size, np.inf)
        else:
            self.n_max = np.asarray(n_max, dtype=float).reshape(-1)
            if self.n_max.size != self.k_thrusters.size:
                raise ValueError("n_max size must match number of thrusters.")
            if np.any(self.n_max <= 0.0):
                raise ValueError("n_max must be positive.")

        self.f_max = self.k_thrusters * (self.n_max ** 2)

    def thrust_from_speed(self, n_cmd: np.ndarray) -> np.ndarray:
        """
        Returns the per-thruster force vector from speed commands.
        """
        n_cmd = np.asarray(n_cmd, dtype=float).reshape(-1)
        if n_cmd.size != self.k_thrusters.size:
            raise ValueError("n_cmd size mismatch.")

        n_cmd = np.clip(n_cmd, -self.n_max, self.n_max)
        return self.k_thrusters * np.abs(n_cmd) * n_cmd

    def speed_from_thrust(self, f_cmd: np.ndarray) -> np.ndarray:
        """
        Returns thruster speed commands corresponding to a thrust command vector.

        This inverts:
            f_i = k_i * |n_i| * n_i
        """
        f_cmd = np.asarray(f_cmd, dtype=float).reshape(-1)
        if f_cmd.size != self.k_thrusters.size:
            raise ValueError("f_cmd size mismatch.")

        n_cmd = np.sign(f_cmd) * np.sqrt(np.abs(f_cmd) / self.k_thrusters)
        n_cmd = np.clip(n_cmd, -self.n_max, self.n_max)
        return n_cmd

    def thrust_to_wrench(self, f_cmd: np.ndarray) -> np.ndarray:
        """
        Returns the BODY-frame wrench generated by a thrust vector.
        """
        f_cmd = np.asarray(f_cmd, dtype=float).reshape(-1)
        if f_cmd.size != self.k_thrusters.size:
            raise ValueError("f_cmd size mismatch.")
        return self.B @ f_cmd

    def tau_from_speed(self, n_cmd: np.ndarray) -> np.ndarray:
        """
        Returns the BODY-frame wrench generated by the current thruster commands.
        """
        f = self.thrust_from_speed(n_cmd)
        return self.B @ f

    def allocate_thrust(self, tau_des: np.ndarray, W: np.ndarray = None) -> np.ndarray:
        """
        Returns a feasible thrust vector that approximately realizes tau_des in weighted
        pseudoinverse form:
            minimize norm( (W*(B*f-tau_des)), 2 )
        and performs elementwise thrust saturation.
        """
        tau_des = np.asarray(tau_des, dtype=float).reshape(6)

        if W is None:
            BW = self.B
            tauW = tau_des
        else:
            W = np.asarray(W, dtype=float)
            if W.shape != (6, 6):
                raise ValueError("W must have shape (6, 6).")
            BW = W @ self.B
            tauW = W @ tau_des

        f_cmd, *_ = np.linalg.lstsq(BW, tauW, rcond=None)
        f_cmd = np.clip(f_cmd, -self.f_max, self.f_max)
        return f_cmd

    def allocate_speed_from_wrench(self, tau_des: np.ndarray, W: np.ndarray = None) -> np.ndarray:
        """
        Returns thruster speed commands approximating tau_des.
        """
        f_cmd = self.allocate_thrust(tau_des, W=W)
        return self.speed_from_thrust(f_cmd)


class PositionController6DOF:
    """
    Computes a BODY-frame wrench from a desired pose command.

    Translational error is rotated into BODY before the gain matrix is applied.
    Angular error remains in Euler coordinates, wrapped to [-pi, pi).

    Channels are independently weighted for DOF awareness, important for
    DSIM BlueROV as 6-thruster BlueROV is only 4DOF actuated.
    """

    def __init__(
        self,
        Kp: np.ndarray,
        Kd: np.ndarray,
        dof_mask: np.ndarray = None,
        eta_error_weight: np.ndarray = None,
        nu_damping_weight: np.ndarray = None,
    ):
        self.Kp = np.asarray(Kp, dtype=float)
        self.Kd = np.asarray(Kd, dtype=float)

        if self.Kp.shape != (6, 6):
            raise ValueError("Kp must have shape (6, 6).")
        if self.Kd.shape != (6, 6):
            raise ValueError("Kd must have shape (6, 6).")

        if dof_mask is None:
            self.dof_mask = np.ones(6)
        else:
            self.dof_mask = np.asarray(dof_mask, dtype=float).reshape(6)

        if eta_error_weight is None:
            self.eta_error_weight = np.ones(6)
        else:
            self.eta_error_weight = np.asarray(eta_error_weight, dtype=float).reshape(6)

        if nu_damping_weight is None:
            self.nu_damping_weight = np.ones(6)
        else:
            self.nu_damping_weight = np.asarray(nu_damping_weight, dtype=float).reshape(6)

        if np.any(self.dof_mask < 0.0):
            raise ValueError("dof_mask must be nonnegative.")
        if np.any(self.eta_error_weight < 0.0):
            raise ValueError("eta_error_weight must be nonnegative.")
        if np.any(self.nu_damping_weight < 0.0):
            raise ValueError("nu_damping_weight must be nonnegative.")

    def compute_tau(self, eta: np.ndarray, nu: np.ndarray, eta_cmd: np.ndarray) -> np.ndarray:
        """
        Returns control wrench for a pose command, currently implemented 
        as a channel-weighted PD controller.
        """
        eta = np.asarray(eta, dtype=float).reshape(6)
        nu = np.asarray(nu, dtype=float).reshape(6)
        eta_cmd = np.asarray(eta_cmd, dtype=float).reshape(6)

        e_eta = wrap_euler_error(eta_cmd - eta)

        phi, theta, psi = eta[3], eta[4], eta[5]
        R_nb = R_n_to_b(phi, theta, psi)

        e_pos_b = R_nb @ e_eta[0:3]
        e_ang = e_eta[3:6]
        e_body = np.concatenate((e_pos_b, e_ang))

        e_dot = -nu

        e_body_weighted = self.dof_mask * self.eta_error_weight * e_body
        e_dot_weighted = self.dof_mask * self.nu_damping_weight * e_dot

        return self.Kp @ e_body_weighted + self.Kd @ e_dot_weighted


class DisturbanceModel:
    """
    Returns an additive BODY-frame disturbance wrench
    for the following terms:
        - constant wrench bias
        - current-relative translational drag
    """

    def __init__(
        self,
        tau_bias: np.ndarray = None,
        current_ned: np.ndarray = None,
        current_drag_diag: np.ndarray = None,
    ):
        self.tau_bias = np.zeros(6) if tau_bias is None else np.asarray(tau_bias, dtype=float).reshape(6)
        self.current_ned = np.zeros(3) if current_ned is None else np.asarray(current_ned, dtype=float).reshape(3)
        self.current_drag_diag = (
            np.zeros(3) if current_drag_diag is None else np.asarray(current_drag_diag, dtype=float).reshape(3)
        )

    def tau_disturbance(self, eta: np.ndarray, nu: np.ndarray) -> np.ndarray:
        """
        Returns total disturbance wrench at current state.
        """
        eta = np.asarray(eta, dtype=float).reshape(6)
        nu = np.asarray(nu, dtype=float).reshape(6)

        phi, theta, psi = eta[3], eta[4], eta[5]
        R_nb = R_n_to_b(phi, theta, psi)
        Vc_b = R_nb @ self.current_ned

        nu_rel_lin = nu[0:3] - Vc_b

        tau_current = np.zeros(6)
        tau_current[0:3] = -self.current_drag_diag * nu_rel_lin

        return self.tau_bias + tau_current


class ControlledFossenSimulator:
    """
    Wraps a Fossen 6-DOF plant with command-side models.

    Supported command paths:
        - thruster-speed command -> tau
        - pose command -> desired tau -> thruster allocation -> achievable tau
    """

    def __init__(
        self,
        model: Fossen6DOFParams,
        thruster_allocator: ThrusterAllocator = None,
        position_controller: PositionController6DOF = None,
        disturbance_model: DisturbanceModel = None,
        allocation_weight: np.ndarray = None,
    ):
        self.model = model
        self.thruster_allocator = thruster_allocator
        self.position_controller = position_controller
        self.disturbance_model = disturbance_model if disturbance_model is not None else DisturbanceModel()

        if allocation_weight is None:
            self.allocation_weight = None
        else:
            self.allocation_weight = np.asarray(allocation_weight, dtype=float)
            if self.allocation_weight.shape != (6, 6):
                raise ValueError("allocation_weight must have shape (6, 6).")

    def total_tau_from_thrusters(self, eta: np.ndarray, nu: np.ndarray, n_cmd: np.ndarray) -> np.ndarray:
        """
        Returns the total wrench for thruster-command mode.
        """
        if self.thruster_allocator is None:
            raise ValueError("thruster_allocator is not configured.")

        tau_cmd = self.thruster_allocator.tau_from_speed(n_cmd)
        tau_dist = self.disturbance_model.tau_disturbance(eta, nu)
        return tau_cmd + tau_dist

    def total_tau_from_position(self, eta: np.ndarray, nu: np.ndarray, eta_cmd: np.ndarray):
        """
        Returns total wrench for pose-command mode after thruster allocation.
        """
        if self.position_controller is None:
            raise ValueError("position_controller is not configured.")
        if self.thruster_allocator is None:
            raise ValueError("thruster_allocator is not configured.")

        tau_des = self.position_controller.compute_tau(eta, nu, eta_cmd)
        n_cmd = self.thruster_allocator.allocate_speed_from_wrench(tau_des,W=self.allocation_weight)
        tau_cmd = self.thruster_allocator.tau_from_speed(n_cmd)

        tau_dist = self.disturbance_model.tau_disturbance(eta, nu)
        tau_total = tau_cmd + tau_dist

        return tau_total, tau_des, n_cmd, tau_cmd

    def step_from_thrusters(self, t: float, x: np.ndarray, n_cmd: np.ndarray, dt: float):
        """
        Advances solver by one step using thruster-speed commands.
        """
        x = np.asarray(x, dtype=float).reshape(12)
        eta = x[0:6]
        nu = x[6:12]

        tau_total = self.total_tau_from_thrusters(eta, nu, n_cmd)
        x_next = self.model.rk4_step(t, x, tau_total, dt)
        return x_next, tau_total

    def step_from_position(self, t: float, x: np.ndarray, eta_cmd: np.ndarray, dt: float):
        """
        Advance solver by one step using pose commands through thruster allocation.
        """
        x = np.asarray(x, dtype=float).reshape(12)
        eta = x[0:6]
        nu = x[6:12]

        tau_total, tau_des, n_cmd, tau_cmd = self.total_tau_from_position(eta, nu, eta_cmd)
        x_next = self.model.rk4_step(t, x, tau_total, dt)

        return x_next, tau_total, tau_des, n_cmd, tau_cmd
